name: Run Salmiac CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  call-salmiac-build-solution-workflow:
    uses: fortanix/salmiac/.github/workflows/build-solution.yml@main
    secrets: inherit